org.gradle.jvmargs=-Xmx6144m --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
kotlin.jvm.target.validation.mode = IGNORE
android.builtInKotlin=true
android.newDsl=true
kotlin.incremental=true
org.gradle.java.home=C:/Users/siddi/.jdks/ms-17.0.15
